### ISSUE TITLE
Couchbase 2.x Driver issues

### ISSUE THREAD

**Issue by rtclauss** [eclipse/jnosql-communication-driver#183]
the Couchbase 2.x driver has entered maintenance mode and they're asking all users to move to the 3.x drivers.  See https://github.com/couchbase/couchbase-java-client/ for more information.

The use of the 2.x Couchbase driver causes issues when deploying a Couchbase JNoSQL app to OpenLiberty with Jaeger as OL and Jaeger both use OpenTracing 0.33 client api while the Couchbase driver uses the 0.31 OpenTracing API. There are breaking API Changes between these two versions and the removal of an API from 0.31 which causes this error when you try to access the Couchbase bucket in your application:

```
java.lang.NoSuchMethodError: io\/opentracing\/Tracer$SpanBuilder.startActive(Z)Lio\/opentracing\/Scope; (loaded from file:\/opt\/ol\/wlp\/lib\/..\/dev\/api\/third-party\/io.openliberty.opentracing.2.0.thirdparty_1.0.68.jar by org.eclipse.osgi.internal.loader.EquinoxClassLoader@598af302[io.openliberty.opentracing.2.0.thirdparty:1.0.68.cl220920220815-1900(id=453)]) called from class com.couchbase.client.java.bucket.api.Utils (loaded from file:\/opt\/ol\/wlp\/output\/defaultServer\/workarea\/org.eclipse.osgi\/64\/data\/cache\/com.ibm.ws.app.manager_72\/.cache\/WEB-INF\/lib\/java-client-2.7.23.jar by com.ibm.ws.classloading.internal.AppClassLoader@98a5f4ab).
    at com.couchbase.client.java.bucket.api.Utils.addRequestSpan(Utils.java:158)
    at com.couchbase.client.java.query.core.N1qlQueryExecutor$2.call(N1qlQueryExecutor.java:202)
    at com.couchbase.client.java.query.core.N1qlQueryExecutor$2.call(N1qlQueryExecutor.java:198)
    at com.couchbase.client.java.util.OnSubscribeDeferAndWatch.call(OnSubscribeDeferAndWatch.java:82)
    at com.couchbase.client.java.util.OnSubscribeDeferAndWatch.call(OnSubscribeDeferAndWatch.java:57)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.unsafeSubscribe(Observable.java:10327)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
    at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
    at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
    at rx.Observable.subscribe(Observable.java:10423)
    at rx.Observable.subscribe(Observable.java:10390)
    at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
    at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
    at com.couchbase.client.java.CouchbaseBucket.query(CouchbaseBucket.java:650)
    at com.couchbase.client.java.CouchbaseBucket.query(CouchbaseBucket.java:564)
    at org.eclipse.jnosql.communication.couchbase.document.DefaultCouchbaseDocumentCollectionManager.select(DefaultCouchbaseDocumentCollectionManager.java:137)
```

This deprecation and removal is noted in the OpenTracing Java repo:
https://github.com/opentracing/opentracing-java/issues/314
https://github.com/opentracing/opentracing-java/pull/339

**Comment by otaviojava** [comment]
Thank you, we'll work to update this version.

**Comment by rtclauss** [comment]
Awesome, thank you!

**Comment by otaviojava** [comment]
We merged it yesterday.
Thank you for the feedback.
