### ISSUE TITLE
Update ES library to the newest version

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql-communication-driver#196]
Update to use the Elasticsearch newest version: 
https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/introduction.html

**Comment by dearrudam** [comment]
Hi @otaviojava ! In my [feat/update-es](https://github.com/dearrudam/jnosql-communication-driver/tree/feat/update-es) branch I've updated it to the newest version, but running the `mvn test` command at `jnosql-elasticsearch-driver` module doesn't work completely. 
The module's tests do, but the `driver-tck-document` tests don't.

Could you give me some help?

According to the log messages, it looks like there are classes from some dependences jars that are using `javax.json.Json` instead of `jakarta.json.Json`:

````text
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentConfigurationTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.282 s - in org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentConfigurationTest
[INFO] Running org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentManagerTest
[]
[INFO] Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 19.425 s - in org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentManagerTest
[INFO] Running org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentManagerFactoryTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s - in org.eclipse.jnosql.communication.elasticsearch.document.ElasticsearchDocumentManagerFactoryTest
[INFO] Running jakarta.nosql.tck.communication.driver.document.DocumentConfigurationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in jakarta.nosql.tck.communication.driver.document.DocumentConfigurationTest
[INFO] Running jakarta.nosql.tck.communication.driver.document.DocumentManagerTest
Dec 27, 2022 5:44:50 AM jakarta.nosql.tck.communication.driver.document.DocumentArgumentProvider get
INFO: Does not find document_ttl.properties as resource, returning an empty configuration
Dec 27, 2022 5:44:50 AM jakarta.nosql.tck.communication.driver.document.DocumentArgumentProvider get
INFO: Does not find document_ttl.properties as resource, returning an empty configuration
Dec 27, 2022 5:44:50 AM jakarta.nosql.tck.communication.driver.document.DocumentArgumentProvider get
INFO: Does not find document_ttl.properties as resource, returning an empty configuration
Dec 27, 2022 5:44:50 AM jakarta.nosql.tck.communication.driver.document.DocumentArgumentProvider get
INFO: Does not find document_ttl.properties as resource, returning an empty configuration
[ERROR] Tests run: 19, Failures: 0, Errors: 8, Skipped: 4, Time elapsed: 0.497 s <<< FAILURE! - in jakarta.nosql.tck.communication.driver.document.DocumentManagerTest
[ERROR] shouldDelete{DocumentArgument}[1]  Time elapsed: 0.183 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldDelete(DocumentManagerTest.java:217)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldDelete(DocumentManagerTest.java:217)

[ERROR] shouldInsert{DocumentArgument}[1]  Time elapsed: 0.073 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldInsert(DocumentManagerTest.java:56)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldInsert(DocumentManagerTest.java:56)

[ERROR] shouldSelect{DocumentArgument}[1]  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldSelect(DocumentManagerTest.java:242)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldSelect(DocumentManagerTest.java:242)

[ERROR] shouldUpdate{DocumentArgument}[1]  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldUpdate(DocumentManagerTest.java:167)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldUpdate(DocumentManagerTest.java:167)

[ERROR] shouldSingleResult{DocumentArgument}[1]  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldSingleResult(DocumentManagerTest.java:267)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldSingleResult(DocumentManagerTest.java:267)

[ERROR] shouldUpdateIterable{DocumentArgument}[1]  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldUpdateIterable(DocumentManagerTest.java:189)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldUpdateIterable(DocumentManagerTest.java:189)

[ERROR] shouldReturnAnErrorEmptySingleResult{DocumentArgument}[1]  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldReturnAnErrorEmptySingleResult(DocumentManagerTest.java:286)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldReturnAnErrorEmptySingleResult(DocumentManagerTest.java:286)

[ERROR] shouldInsertIterable{DocumentArgument}[1]  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/json/Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldInsertIterable(DocumentManagerTest.java:107)
Caused by: java.lang.ClassNotFoundException: javax.json.Json
        at jakarta.nosql.tck.communication.driver.document.DocumentManagerTest.shouldInsertIterable(DocumentManagerTest.java:107)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DocumentManagerTest.shouldDelete:217 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldInsertIterable:107 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldInsert:56 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldReturnAnErrorEmptySingleResult:286 » NoClassDefFound
[ERROR]   DocumentManagerTest.shouldSelect:242 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldSingleResult:267 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldUpdateIterable:189 » NoClassDefFound javax/json/Json
[ERROR]   DocumentManagerTest.shouldUpdate:167 » NoClassDefFound javax/json/Json
[INFO] 
[ERROR] Tests run: 44, Failures: 0, Errors: 8, Skipped: 4
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.775 s
[INFO] Finished at: 2022-12-27T05:44:51-03:00
[INFO] ------------------------------------------------------------------------
````

**Comment by otaviojava** [comment]
Hey @max, for sure;

We still need to update to the big bang version; we plan to move next year when more vendors are using it.

So two options:

* Keep using it before the Big bang, and next year we will update everything as one
*  comment the line 118 in the pom.xml:   `<dependency>jakarta.nosql.tck.communication.driver:driver-tck-document</dependency>`

**Comment by otaviojava** [comment]
My recommendation is before using a big bang; we create a task force to update everything as we did to improve the documentation.

**Comment by dearrudam** [comment]
@otaviojava thank you so much!!!

I'm going to change my branch to use the `javax.json` classes in order to make the TCK tests work! I think that's the better option by now, and later we could be updating it

**Comment by otaviojava** [comment]
Nice, we've released the new version.
The significant bang upgrade will be the following code step.
